name: Generate contribution snake

on:
  workflow_dispatch:

  schedule:
    - cron: "31 3 * * 1"

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: 2400030948
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-light&color_snake=%2339D353
            output/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2339D353

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: refresh contribution snake"
          add: "output"